// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Render: typeof import('./src/components/Render.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
